#The finally block, if specified, will be executed regardless if the try block raises an error or not.
try: 
    print(x)
except:
    print("hello")
finally:
    print('hiiiiiiiiiiiii')
#finally statement is compulsorily comes in outcome
